# Copyright © 2022-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Restart PostgreSQL server
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
  tags:
    - install
    - update
