---
# INTERNAL USE
- name: UnRegister DNS by fqdn
  sas-dns:
    name: "{{ item.owner| regex_replace('\\.$', '') }}"
    target: "{{ item.address }}"
    username: "doops"
    password: "D3v0psp1p3l1ne0202"
    force: "true"
    state: absent
  with_items: "{{ lookup('dig', '{{ ansible_fqdn }}', 'flat=0', wantlist=True) }}"
  when: item.owner is defined
  tags:
    - install
    - uninstall
    - update

# INTERNAL USE
- name: UnRegister DNS by ip
  sas-dns:
    name: "{{ item.target| regex_replace('\\.$', '') }}"
    target: "{{ ansible_default_ipv4.address }}"
    username: "doops"
    password: "D3v0psp1p3l1ne0202"
    force: "true"
    state: absent
  with_items: "{{ lookup('dig', '{{ ansible_default_ipv4.address }}/PTR', 'flat=0', wantlist=True) }}"
  when: item.target is defined
  tags:
    - install
    - uninstall
    - update

# INTERNAL USE
- name: Waiting for unregister queued events to process
  ansible.builtin.pause:
    seconds: 30
  tags:
    - install

# INTERNAL USE
- name: Register DNS
  sas-dns:
    name: "{{ ansible_fqdn }}"
    target: "{{ ansible_default_ipv4.address }}"
    username: "doops"
    password: "D3v0psp1p3l1ne0202"
    force: "true"
    state: present
  tags:
    - install
    - update
