#!/usr/bin/env bash

# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

# oIFS="$IFS"; IFS=" ," ; set -- $1 ; IFS="$oIFS"

# Catch errors
set -e

# Global variables
ARGS="$@"
BASEDIR="$(pwd)"
BINDIR="$BASEDIR/bin"
SYSTEM="${SYSTEM:-bare_metal}"

# Flags
creation_flag=false
update_flag=false
destruction_flag=false
external_flag=false
validated_args=null

# Determine how the script is being run -- natively or inside a Docker container
if [[ "$IAC_TOOLING" == "docker" ]]; then
  WORKDIR="/workspace"
  K8S_TOOL_BASE="/viya4-iac-k8s"
else
  WORKDIR="$BASEDIR"
  K8S_TOOL_BASE="$WORKDIR"
fi

TFVARS="$WORKDIR/terraform.tfvars"
TFSTATE="$WORKDIR/terraform.tfstate"
ANSIBLE_INVENTORY="$WORKDIR/inventory"
ANSIBLE_VARS="@$WORKDIR/ansible-vars.yaml"
TF_COMPAT_ARGS=()
# main.tf lives alongside the Terraform root module in BASEDIR (the baked image
# at /viya4-iac-k8s in Docker).  WORKDIR is the user-mounted volume (/workspace)
# and does NOT contain main.tf.
MAIN_TF="$BASEDIR/main.tf"
MAIN_TF_BACKUP="$BASEDIR/.main.tf.iac-backup"
# In Docker mode WORKDIR=/workspace (the mounted volume) but terraform runs from
# BASEDIR=/viya4-iac-k8s (the baked image dir).  The stub must live in BASEDIR
# so that terraform can discover it during static module validation.
RUNTIME_STUB_TF="$BASEDIR/runtime-provider-stubs.tf"

# Functions

# vSphere items (terraform)
gather_tf_creds() {
    if [[ "$SYSTEM" == "vsphere" ]]; then
      if [[ -z "$VSPHERE_USER" ]]; then 
          read -p 'vsphere_user: ' VSPHERE_USER
      fi
      echo

      if [[ -z "$VSPHERE_PASSWORD" ]]; then 
          read -sp 'vsphere_password: ' VSPHERE_PASSWORD
      fi
      echo

      export TF_VAR_vsphere_user=$VSPHERE_USER
      export TF_VAR_vsphere_password=$VSPHERE_PASSWORD
    fi

    if [[ "$SYSTEM" == "openstack" ]]; then
      # Auto-source the standard creds file if present and env isn't already populated
      if [[ -f "$HOME/.openstack_creds.env" ]] && [[ -z "$OS_AUTH_URL" ]]; then
        set -a
        # shellcheck source=/dev/null
        source "$HOME/.openstack_creds.env"
        set +a
      fi

      if [[ -z "$OS_USERNAME" ]]; then
          read -p 'openstack_user_name: ' OS_USERNAME
      fi
      echo

      if [[ -z "$OS_PASSWORD" ]]; then
          read -sp 'openstack_password: ' OS_PASSWORD
      fi
      echo

      export TF_VAR_openstack_user_name=$OS_USERNAME
      export TF_VAR_openstack_password=$OS_PASSWORD
      export TF_VAR_openstack_auth_url=${OS_AUTH_URL:-$TF_VAR_openstack_auth_url}
      export TF_VAR_openstack_tenant_name=${OS_PROJECT_NAME:-$TF_VAR_openstack_tenant_name}
      export TF_VAR_openstack_domain_name=${OS_USER_DOMAIN_NAME:-$TF_VAR_openstack_domain_name}
      export TF_VAR_openstack_region=${OS_REGION_NAME:-$TF_VAR_openstack_region}
      export TF_VAR_openstack_insecure=${OS_INSECURE:-true}

      # Terraform still discovers the vSphere provider from sibling modules in the
      # root graph even for OpenStack runs. Provide placeholder values so it does
      # not prompt for configuration; no vSphere resources are instantiated when
      # deployment_type=openstack.
      export TF_VAR_vsphere_user=${TF_VAR_vsphere_user:-openstack-unused}
      export TF_VAR_vsphere_password=${TF_VAR_vsphere_password:-openstack-unused}
      export TF_VAR_vsphere_server=${TF_VAR_vsphere_server:-vsphere.invalid}
    fi

    # Only override TF_VAR_ansible_user/password if ANSIBLE_USER is already known.
    # Exporting an empty value here would clobber TF_VAR_ansible_user injected via
    # --env-file (Docker) or the environment, causing gather_ans_creds() to prompt.
    if [[ -n "$ANSIBLE_USER"     ]]; then export TF_VAR_ansible_user=$ANSIBLE_USER; fi
    if [[ -n "$ANSIBLE_PASSWORD" ]]; then export TF_VAR_ansible_password=$ANSIBLE_PASSWORD; fi
}

write_provider_config() {
  if [[ "$SYSTEM" == "openstack" ]]; then
    cat > "$BASEDIR/provider.tf" << 'PROVIDEREOF'
# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Auto-generated by oss-k8s.sh for SYSTEM=openstack -- do not edit manually.

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    openstack = {
      source  = "terraform-provider-openstack/openstack"
      version = "~> 3.0"
    }
  }
}

provider "openstack" {
  auth_url    = var.openstack_auth_url
  user_name   = var.openstack_user_name
  password    = var.openstack_password
  tenant_name = var.openstack_tenant_name
  domain_name = var.openstack_domain_name
  region      = var.openstack_region
  insecure    = var.openstack_insecure
  cacert_file = var.openstack_cacert_file
}
PROVIDEREOF
  elif [[ "$SYSTEM" == "vsphere" ]]; then
    cat > "$BASEDIR/provider.tf" << 'PROVIDEREOF'
# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
# Auto-generated by oss-k8s.sh for SYSTEM=vsphere -- do not edit manually.

terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    vsphere = {
      source  = "hashicorp/vsphere"
      version = "~> 2.6"
    }
  }
}

provider "vsphere" {
  user               = var.vsphere_user
  password           = var.vsphere_password
  vsphere_server     = var.vsphere_server
  allow_unverified_ssl = true
}
PROVIDEREOF
  fi
}

write_main_config() {
  if [[ ! -f "$MAIN_TF_BACKUP" ]]; then
    cp "$MAIN_TF" "$MAIN_TF_BACKUP"
  fi

  rm -f "$RUNTIME_STUB_TF"

  if [[ "$SYSTEM" == "openstack" ]]; then
    awk '
      /^# vSphere – provider data sources/ { skip = 1; next }
      /^# OpenStack – Kubernetes node modules/ { skip = 0 }
      !skip { print }
    ' "$MAIN_TF_BACKUP" > "$MAIN_TF"

    cat > "$RUNTIME_STUB_TF" << 'STUBEOF'
module "control_plane" {
  source = "./modules/noop"
  for_each = var.deployment_type == "openstack" ? local.control_plane_nodes : {}
  ip_addresses = []
}

module "system" {
  source = "./modules/noop"
  for_each = var.deployment_type == "openstack" ? local.system_nodes : {}
  ip_addresses = []
}

module "node" {
  source = "./modules/noop"
  for_each = var.deployment_type == "openstack" ? local.nodes : {}
  ip_addresses = []
}
STUBEOF
  elif [[ "$SYSTEM" == "vsphere" ]]; then
    awk '
      /^# OpenStack – Kubernetes node modules/ { skip = 1; next }
      /^# Ansible inventory \+ vars files/ { skip = 0 }
      !skip { print }
    ' "$MAIN_TF_BACKUP" > "$MAIN_TF"
  else
    cp "$MAIN_TF_BACKUP" "$MAIN_TF"
  fi
}

restore_main_config() {
  rm -f "$RUNTIME_STUB_TF"

  if [[ -f "$MAIN_TF_BACKUP" ]]; then
    mv "$MAIN_TF_BACKUP" "$MAIN_TF"
  fi
}

build_terraform_compat_args() {
  TF_COMPAT_ARGS=()

  if [[ "$SYSTEM" == "openstack" ]]; then
    TF_COMPAT_ARGS+=(
      -var "vsphere_user=${TF_VAR_vsphere_user:-openstack-unused}"
      -var "vsphere_password=${TF_VAR_vsphere_password:-openstack-unused}"
      -var "vsphere_server=${TF_VAR_vsphere_server:-vsphere.invalid}"
    )
  fi
}

terraform_prep() {
  write_main_config
  write_provider_config
  gather_tf_creds
  build_terraform_compat_args
  terraform init
}

terraform_up() {
    terraform_prep
    # In Docker mode BASEDIR=/viya4-iac-k8s but WORKDIR=/workspace (the mounted volume).
    # Pass inventory and ansible_vars as absolute paths into WORKDIR so the files land
    # where the Ansible phase (which uses WORKDIR) can find them.
    local TF_OUTPUT_ARGS=()
    if [[ "$IAC_TOOLING" == "docker" ]]; then
      TF_OUTPUT_ARGS=(
        -var "inventory=$WORKDIR/inventory"
        -var "ansible_vars=$WORKDIR/ansible-vars.yaml"
      )
    fi
    terraform apply -parallelism=20 -state $TFSTATE -auto-approve "${TF_COMPAT_ARGS[@]}" "${TF_OUTPUT_ARGS[@]}" -var "deployment_type=$SYSTEM" -var-file $TFVARS
    echo "Wait for OS startup - Sleeping for 60 seconds"
    sleep 60
    if [[ "$SYSTEM" == "openstack" ]]; then
        patch_vip_allowed_pairs
    fi
}

# allocate_vip_floating_ip - Allocate two OpenStack floating IPs:
#   1. cluster_vip_ip      — kube-vip control-plane HA VIP
#   2. cluster_lb_addresses — kube-vip cloud-provider LoadBalancer service VIP
# Each IP is only allocated if not already set in terraform.tfvars.
# The floating IPs are created unassociated (no server) — they exist solely to
# reserve clean IPs that OpenStack tracks, which can then be registered in
# names.sas.com under the unx.sas.com domain.
allocate_vip_floating_ip() {
    local NETWORK
    NETWORK=$(grep -E '^\s*openstack_network_name\s*=' "$TFVARS" 2>/dev/null | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/' | tr -d ' "')
    if [[ -z "$NETWORK" ]]; then
        echo "allocate_vip_floating_ip: openstack_network_name not set in $TFVARS, skipping."
        return 0
    fi

    # ------------------------------------------------------------------
    # [1] cluster_vip_ip — control-plane HA VIP
    # ------------------------------------------------------------------
    local CURRENT_VIP
    CURRENT_VIP=$(grep -E '^\s*cluster_vip_ip\s*=' "$TFVARS" 2>/dev/null | head -1 | sed 's/.*=\s*//' | tr -d ' "')
    local VIP
    if [[ -n "$CURRENT_VIP" && "$CURRENT_VIP" != "null" ]]; then
        echo "allocate_vip_floating_ip: [cluster_vip_ip]      already set to $CURRENT_VIP — skipping allocation."
        VIP="$CURRENT_VIP"
    else
        echo "allocate_vip_floating_ip: allocating floating IP for cluster_vip_ip (control-plane HA VIP)..."
        local FIP_JSON1
        FIP_JSON1=$(openstack floating ip create "$NETWORK" -f json 2>/dev/null)
        VIP=$(echo "$FIP_JSON1" | python3 -c "import sys,json; print(json.load(sys.stdin).get('floating_ip_address',''))" 2>/dev/null)
        if [[ -z "$VIP" ]]; then
            echo "allocate_vip_floating_ip: failed to allocate cluster_vip_ip, skipping."
            return 0
        fi
        if grep -qE '^\s*#?\s*cluster_vip_ip\s*=' "$TFVARS"; then
            sed -i "s|^\s*#\?\s*cluster_vip_ip\s*=.*|cluster_vip_ip      = \"${VIP}\"|" "$TFVARS"
        else
            sed -i "/cluster_vip_version/a cluster_vip_ip      = \"${VIP}\"" "$TFVARS"
        fi
        echo "allocate_vip_floating_ip: [cluster_vip_ip]      allocated $VIP — written to $TFVARS"
    fi

    # ------------------------------------------------------------------
    # [2] cluster_lb_addresses — LoadBalancer service VIP
    # ------------------------------------------------------------------
    local CURRENT_LB
    CURRENT_LB=$(grep -E '^\s*cluster_lb_addresses\s*=' "$TFVARS" 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -1)
    local LB_VIP
    if [[ -n "$CURRENT_LB" ]]; then
        echo "allocate_vip_floating_ip: [cluster_lb_addresses] already set to $CURRENT_LB — skipping allocation."
        LB_VIP="$CURRENT_LB"
    else
        echo "allocate_vip_floating_ip: allocating floating IP for cluster_lb_addresses (LoadBalancer service VIP)..."
        local FIP_JSON2
        FIP_JSON2=$(openstack floating ip create "$NETWORK" -f json 2>/dev/null)
        LB_VIP=$(echo "$FIP_JSON2" | python3 -c "import sys,json; print(json.load(sys.stdin).get('floating_ip_address',''))" 2>/dev/null)
        if [[ -z "$LB_VIP" ]]; then
            echo "allocate_vip_floating_ip: failed to allocate cluster_lb_addresses IP, skipping."
            return 0
        fi
        if grep -qE '^\s*cluster_lb_addresses\s*=' "$TFVARS"; then
            sed -i "s|^\s*cluster_lb_addresses\s*=.*|cluster_lb_addresses = [\"range-global: ${LB_VIP}-${LB_VIP}\"]|" "$TFVARS"
        else
            sed -i "/cluster_lb_type/a cluster_lb_addresses = [\"range-global: ${LB_VIP}-${LB_VIP}\"]" "$TFVARS"
        fi
        echo "allocate_vip_floating_ip: [cluster_lb_addresses] allocated $LB_VIP — written to $TFVARS"
    fi

    echo ""
    echo "  *** ACTION REQUIRED ***"
    echo "  Register both VIPs in names.sas.com (unx.sas.com domain):"
    echo "    [1] cluster_vip_ip      $VIP  ->  <prefix>-vip.unx.sas.com"
    echo "    [2] cluster_lb_addresses $LB_VIP  ->  <prefix>-lb.unx.sas.com"
    echo "  Then set cluster_vip_fqdn in $TFVARS to match."
    echo "  *** ******************** ***"
    echo ""
}

# patch_vip_allowed_pairs - Add the kube-vip VIP to allowed_address_pairs on all
# control plane Neutron ports.  The Neutron policy in most environments disallows
# setting allowed_address_pairs at port-creation time, but allows PUTting them on
# existing ports.  This function runs after terraform_up so the ports already exist.
patch_vip_allowed_pairs() {
    local VIP
    VIP=$(grep -E '^\s*cluster_vip_ip\s*=' "$TFVARS" 2>/dev/null | head -1 | sed 's/.*=\s*//' | tr -d ' "')
    if [[ -z "$VIP" || "$VIP" == "null" ]]; then
        echo "patch_vip_allowed_pairs: cluster_vip_ip not set in $TFVARS, skipping."
        return 0
    fi

    local NEUTRON_URL TOKEN TOKEN_RESPONSE
    TOKEN_RESPONSE=$(curl -sk -i -X POST "${OS_AUTH_URL}auth/tokens" \
      -H "Content-Type: application/json" \
      -d "{\"auth\":{\"identity\":{\"methods\":[\"password\"],\"password\":{\"user\":{\"name\":\"${OS_USERNAME}\",\"domain\":{\"name\":\"${OS_USER_DOMAIN_NAME}\"},\"password\":\"${OS_PASSWORD}\"}}},\"scope\":{\"project\":{\"name\":\"${OS_PROJECT_NAME}\",\"domain\":{\"name\":\"${OS_USER_DOMAIN_NAME}\"}}}}}" 2>/dev/null)

    TOKEN=$(echo "$TOKEN_RESPONSE" | grep -i "x-subject-token" | awk '{print $2}' | tr -d '\r\n')
    NEUTRON_URL=$(echo "$TOKEN_RESPONSE" | python3 -c "
import sys, json
data = sys.stdin.read()
body = json.loads(data[data.find('{'):])
for svc in body.get('token',{}).get('catalog',[]):
    if svc.get('type') == 'network':
        for ep in svc.get('endpoints',[]):
            if ep.get('interface') == 'public':
                print(ep.get('url',''))
                break
" 2>/dev/null)

    if [[ -z "$TOKEN" ]] || [[ -z "$NEUTRON_URL" ]]; then
        echo "patch_vip_allowed_pairs: could not obtain Keystone token or Neutron URL, skipping."
        return 0
    fi

    local PREFIX
    PREFIX=$(grep -E '^\s*prefix\s*=' "$TFVARS" 2>/dev/null | head -1 | sed 's/.*=\s*"\(.*\)".*/\1/' | tr -d ' "')
    local CLUSTER_NAME="${PREFIX}-oss"

    # Build allowed_address_pairs list: VIP + all IPs from cluster_lb_addresses ranges.
    # cluster_lb_addresses format: ["range-global: A.B.C.D-A.B.C.E", ...]
    # We extract the first IP of each range as representative (kube-vip ARPs from worker nodes,
    # but the control-plane port must also allow the IPs so OpenStack passes the traffic).
    local LB_IPS=()
    while IFS= read -r lb_line; do
        # Extract first IP from range (e.g. "range-global: 10.119.130.154-10.119.130.154" -> "10.119.130.154")
        local first_ip
        first_ip=$(echo "$lb_line" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        local last_ip
        last_ip=$(echo "$lb_line" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | tail -1)
        # Expand simple single-octet ranges (e.g. 154-156) up to 16 IPs
        if [[ -n "$first_ip" && -n "$last_ip" && "$first_ip" != "$last_ip" ]]; then
            local base="${first_ip%.*}"
            local start_oct="${first_ip##*.}"
            local end_oct="${last_ip##*.}"
            for oct in $(seq "$start_oct" "$end_oct"); do
                LB_IPS+=("${base}.${oct}")
            done
        elif [[ -n "$first_ip" ]]; then
            LB_IPS+=("$first_ip")
        fi
    done < <(grep -E '^\s*cluster_lb_addresses' "$TFVARS" 2>/dev/null | grep -oE '"[^"]*range[^"]*"' | tr -d '"')

    # Build JSON array: VIP first, then LB IPs (deduplicated)
    local PAIRS_JSON="{\"ip_address\":\"${VIP}\"}"
    for lb_ip in "${LB_IPS[@]}"; do
        [[ "$lb_ip" == "$VIP" ]] && continue   # skip if same as VIP
        PAIRS_JSON+=",{\"ip_address\":\"${lb_ip}\"}"
    done
    local PATCH_BODY="{\"port\":{\"allowed_address_pairs\":[${PAIRS_JSON}]}}"

    echo "patch_vip_allowed_pairs: patching control-plane ports for cluster '${CLUSTER_NAME}' with VIP ${VIP} + LB IPs [${LB_IPS[*]}]"

    # Neutron ?name= filter is exact-match only, so fetch all ports and filter client-side.
    local PORT_LIST
    PORT_LIST=$(curl -sk -H "X-Auth-Token: $TOKEN" \
      "${NEUTRON_URL}/v2.0/ports" | \
      python3 -c "
import sys, json
prefix = '${CLUSTER_NAME}-control-plane'
for p in json.load(sys.stdin).get('ports', []):
    if p.get('name','').startswith(prefix):
        print(p['id'], p['name'])
" 2>/dev/null)

    if [[ -z "$PORT_LIST" ]]; then
        echo "patch_vip_allowed_pairs: no control-plane ports found, skipping."
        return 0
    fi

    while IFS= read -r line; do
        PORT_ID=$(echo "$line" | awk '{print $1}')
        PORT_NAME=$(echo "$line" | awk '{print $2}')
        RESULT=$(curl -sk -X PUT \
          -H "X-Auth-Token: $TOKEN" \
          -H "Content-Type: application/json" \
          -d "$PATCH_BODY" \
          "${NEUTRON_URL}/v2.0/ports/${PORT_ID}" | \
          python3 -c "import sys,json; d=json.load(sys.stdin); p=d.get('port',{}); print('OK' if p.get('allowed_address_pairs') else str(d.get('NeutronError','unknown error')))" 2>/dev/null)
        echo "  port $PORT_NAME ($PORT_ID): $RESULT"
    done <<< "$PORT_LIST"
}

terraform_down() {
    terraform_prep
    local TF_OUTPUT_ARGS=()
    if [[ "$IAC_TOOLING" == "docker" ]]; then
      TF_OUTPUT_ARGS=(
        -var "inventory=$WORKDIR/inventory"
        -var "ansible_vars=$WORKDIR/ansible-vars.yaml"
      )
    fi
    terraform destroy -parallelism=20 -state $TFSTATE -auto-approve "${TF_COMPAT_ARGS[@]}" "${TF_OUTPUT_ARGS[@]}" -var "deployment_type=$SYSTEM" -var-file $TFVARS
}

# bare_metal items (ansible)
gather_ans_creds() {
    # Source the creds file so TF_VAR_ansible_user/TF_VAR_ansible_password are available
    if [[ -f "$HOME/.openstack_creds.env" ]] && [[ -z "$TF_VAR_ansible_user" ]]; then
      set -a
      # shellcheck source=/dev/null
      source "$HOME/.openstack_creds.env"
      set +a
    fi

    # Accept either ANSIBLE_USER or TF_VAR_ansible_user (OpenStack env file uses the latter)
    ANSIBLE_USER="${ANSIBLE_USER:-$TF_VAR_ansible_user}"
    ANSIBLE_PASSWORD="${ANSIBLE_PASSWORD:-$TF_VAR_ansible_password}"

    if [[ -z "$ANSIBLE_USER" ]]; then 
        read -p 'ansible_user: ' ANSIBLE_USER
    fi
    echo

    if [[ -z "$ANSIBLE_PASSWORD" ]]; then 
        read -sp 'ansible_password: ' ANSIBLE_PASSWORD
    fi
    echo
}

trap restore_main_config EXIT

# vSphere and bare-metal items
ansible_prep() {
    gather_ans_creds
    ansible-galaxy collection install -r "$BASEDIR/requirements.yaml"
}

clean_up() {
    rm -rf $WORKDIR/*-oss-kubeconfig.conf
    rm -rf $WORKDIR/sas-iac-buildinfo-cm.yaml
}

help() {
  echo ""
  echo "Usage: $0 [apply|setup|install|update|uninstall|cleanup|destroy|helm|k|tf]"
  echo ""
  echo "  Actions           - Items and their meanings"
  echo ""
  echo "    apply           - IaC creation                     : vSphere/vCenter or OpenStack"
  echo "    setup           - System and software setup        : systems"
  echo "    install         - Kubernetes install               : systems"
  echo "    update          - System and/or Kubernetes updates : systems"
  echo "    uninstall       - Kubernetes uninstall             : systems"
  echo "    cleanup         - System and software cleanup      : systems"
  echo "    destroy         - IaC destruction                  : vSphere/vCenter or OpenStack"
  echo ""
  echo "  Action groupings  - These items can be run together."
  echo "                      Alternate combinations are not allowed."
  echo ""
  echo "  creation items    - [apply setup install]"
  echo "  update items      - [update]"
  echo "  destruction items - [uninstall cleanup destroy]"
  echo ""
  echo "  Tooling - Integrated tools"
  echo ""
  echo "    helm            - Helm                             : kubernetes"
  echo "    k               - kubectl                          : kubernetes"
  echo "    tf              - Terraform                        : vSphere/vCenter or OpenStack"
  echo ""
  echo "  Environment variables"
  echo ""
  echo "    SYSTEM          - Deployment type: vsphere, openstack, or bare_metal (default)"
  echo "                      Set before running: export SYSTEM=openstack"
  echo ""
  exit 1
}

# Process input
if [ "$#" -eq 0 ]; then
  help
fi

# Processing command line arguments
#
# Actions are:
#
#   apply     - IaC creation
#   setup     - System and software setup
#   install   - Kubernetes install
#   update    - System and/or Kubernetes update
#   uninstall - Kubernetes uninstall
#   cleanup   - System and software cleanup
#   destroy   - IaC Destruction
#


# Determine what arguments have been passed and store
# those values in a known order
for arg in ${ARGS[@]}; do
  if [[ "$arg" == "apply" ]]; then
    arguments[0]=apply
  fi
  if [[ "$arg" == "setup" ]]; then
    arguments[1]=setup
  fi
  if [[ "$arg" == "install" ]]; then
    arguments[2]=install
  fi
  if [[ "$arg" == "update" ]]; then
    arguments[3]=update
  fi
  if [[ "$arg" == "uninstall" ]]; then
    arguments[4]=uninstall
  fi
  if [[ "$arg" == "cleanup" ]]; then
    arguments[5]=cleanup
  fi
  if [[ "$arg" == "destroy" ]]; then
    arguments[6]=destroy
  fi
done

#
# Check on argument combinations
#
#  apply,setup,install       - valid
#  update                    - valid
#  uninstall,cleanup,destroy - valid
#
# No other combinations are allowed
#
creation_items=( apply setup install )
update_items=( update )
destruction_items=( uninstall cleanup destroy )
external_items=( k tf helm )

for item in ${arguments[@]}; do
  if [[ " ${creation_items[*]} " =~ " $item " ]]; then
    creation_flag=true
  fi
  if [[ " ${update_items[*]} " =~ " $item " ]]; then
    update_flag=true
  fi
  if [[ " ${destruction_items[*]} " =~ " $item " ]]; then
    destruction_flag=true
  fi
done

for item in ${ARGS[@]}; do
  if [[ " ${external_items[*]} " =~ " $item " ]]; then
    external_flag=true
  fi
done

# Validating argument combinations
if [ "$creation_flag" = true ]; then
  if [ "$update_flag" = true ] || [ "$destruction_flag" = true ]; then
    validated_args=false
  else
    validated_args=true
  fi
fi

if [ "$update_flag" = true ]; then
  if [ "$creation_flag" = true ] || [ "$destruction_flag" = true ]; then
    validated_args=false
  else
    validated_args=true
  fi
fi

if [ "$destruction_flag" = true ]; then
  if [ "$creation_flag" = true ] || [ "$update_flag" = true ]; then
    validated_args=false
  else
    validated_args=true
  fi
fi

if [ "$external_flag" = true ]; then
  if [ "$creation_flag" = true ] || [ "$update_flag" = true ] || [ "$destruction_flag" = true ]; then
    validated_args=false
  else
    validated_args=true
  fi
fi

if [ "$validated_args" != true ]; then
  echo "The arguments and/or combination of arguments is invalid: $ARGS"
  echo ""
  help
fi

if [ "$external_flag" = true ] && [ "$validated_args" = true ]; then
  # Check to see if the request is for tooling help
  while [ "${#ARGS[@]}" -gt 0 ]; do
    case "$1" in
      helm )
        helm ${@:2}
        exit "$?"
        ;;
      k|kubtctl )
        kubectl ${@:2}
        exit "$?"
        ;;
      tf|terraform )
        terraform $2 -state $TFSTATE ${@:3}
        exit "$?"
        ;;
    esac
  done    
fi

# Process the arguments
for item in "${arguments[@]}"; do
  # apply - Create infrastructure
  if [[ "$item" == "apply" ]]; then
    echo "Infrastructure - Virtual hardware"
    if [[ -z "$SYSTEM" || "$SYSTEM" == "bare_metal" ]]; then
      SYSTEM=vsphere
    fi
    terraform_up
  fi
  # setup - Baseline systems
  if [[ "$item" == "setup" ]]; then
    ansible_prep
    ansible-playbook -i $ANSIBLE_INVENTORY --extra-vars "deployment_type=$SYSTEM" --extra-vars $ANSIBLE_VARS $BASEDIR/playbooks/systems-install.yaml --flush-cache --tags install
  fi
  # install - Install kubernetes
  if [[ "$item" == "install" ]]; then
    ansible_prep
    ansible-playbook -i $ANSIBLE_INVENTORY --extra-vars "deployment_type=$SYSTEM" --extra-vars "iac_tooling=$IAC_TOOLING" --extra-vars "iac_inventory_dir=$WORKDIR" --extra-vars "k8s_tool_base"=$K8S_TOOL_BASE --extra-vars $ANSIBLE_VARS $BASEDIR/playbooks/kubernetes-install.yaml --flush-cache --tags install
  fi
  # update- Update systems and/or kubernetes
  if [[ "$item" == "update" ]]; then
    echo "TODO: update"
  fi
  # uninstall - Uninstall kubernetes
  if [[ "$item" == "uninstall" ]]; then
    ansible_prep
    ansible-playbook -i $ANSIBLE_INVENTORY --extra-vars "deployment_type=$SYSTEM" --extra-vars "iac_tooling=$IAC_TOOLING" --extra-vars "iac_inventory_dir=$WORKDIR" --extra-vars "k8s_tool_base"=$K8S_TOOL_BASE --extra-vars $ANSIBLE_VARS $BASEDIR/playbooks/kubernetes-uninstall.yaml --flush-cache --tags uninstall
    rm -rf *-oss-kubeconfig.conf 2>&1 > /dev/null
    rm -rf sas-iac-buildinfo-cm.yaml 2>&1 > /dev/null
  fi
  # cleanup - 
  if [[ "$item" == "cleanup" ]]; then
    echo "TODO: cleanup"
  fi
  # destroy - Destroy infrastructure
  if [[ "$item" == "destroy" ]]; then
    if [[ -z "$SYSTEM" || "$SYSTEM" == "bare_metal" ]]; then
      SYSTEM=vsphere
    fi
    if [[ -e $TFSTATE ]]; then
      if [[ "$IAC_TOOLING" != "docker" ]]; then
        read -p 'Are you absolutely sure: ' CONFIRMATION
        if [[ "$CONFIRMATION" == "y" || "$CONFIRMATION" == "yes" ]]; then
          echo "Destroying cluster and infra"
          terraform_down
        else
          echo "You did not opt to run destroy"
          exit 1
        fi
      else
        echo "Destroying cluster and infra"
        terraform_down
      fi
    else
      echo "No infrastructure to destroy. Thanks for playing ;)"
      exit 0
    fi
    # Clean up
    clean_up
    rm -rf "$TFSTATE" 2>&1 > /dev/null
    rm -rf "$TFSTATE.backup" 2>&1 > /dev/null
    rm -rf $BASEDIR/ssl-cert-sas-*-pgsql.{key,pem} 2>&1 > /dev/null
    break
  fi
done

# while [ "$#" -gt 0 ]; do
#   case "$1" in
#     helm )
#       helm ${@:2}
#       break
#       ;;
#     k|kubtctl )
#       kubectl ${@:2}
#       break
#       ;;
#     tf|terraform )
#       terraform $2 -state $TFSTATE ${@:3}
#       break
#       ;;
#     * )
#       echo "Please enter the correct arguments."
#       break
#       ;;
#   esac
# done
