---
collections:
  - name: community.general
    version: 4.2.0
  - name: community.postgresql
    version: 1.7.1
  - name: kubernetes.core # community.kubernetes
    version: 2.2.2 # 1.2.1
  - name: ansible.posix
    version: 1.3.0
  - name: ansible.utils
    version: 2.3.0
