---
collections:
  - name: community.general
    version: 8.4.0 # 5.6.0 # 5.5.0 4.8.0 # 4.2.0
    # The collections below are all included in community.general
  - name: community.postgresql
    version: 3.3.0 # 2.2.0 # 1.7.2 # 1.7.1
  - name: kubernetes.core # community.kubernetes
    version: 2.4.0 # 2.3.2 # 2.3.0 # 1.2.1, 2.2.2
  - name: ansible.posix
    version: 1.5.4 # 1.4.0 # 1.3.0
  - name: ansible.utils
    version: 2.12.0 # 2.6.1 # 2.6.0 # 2.3.0
