# =============================================================================
# Sample tfvars for deploying a SAS Viya 4 Kubernetes cluster on OpenStack
# using floating IPs (no pre-assigned static IPs required).
#
# Copy this file, fill in the values marked with "" or <>, and run:
#   terraform init
#   terraform plan -var-file=<your-file>.tfvars
#   terraform apply -var-file=<your-file>.tfvars
# =============================================================================

# Deployment type - DO NOT CHANGE
deployment_type = "openstack"

# General items
ansible_user     = ""  # OS user for Ansible SSH access (e.g. ubuntu)
ansible_password = ""  # Leave empty if using SSH key-based auth
prefix           = "v4-k8s-os" # Infra prefix – lowercase alphanumeric + hyphens

# OpenStack credentials / endpoint
openstack_auth_url    = "" # e.g. https://openstack.example.com:5000/v3
openstack_user_name   = "" # OpenStack username
openstack_password    = "" # OpenStack password
openstack_tenant_name = "" # Project / tenant name
openstack_domain_name = "Default"
openstack_region      = "" # e.g. RegionOne
openstack_insecure    = false # Set true only if using self-signed certs
# openstack_cacert_file = "/path/to/ca.crt"  # Uncomment if needed

# OpenStack compute / network settings
openstack_image_name       = "" # e.g. "Ubuntu 22.04 LTS"
openstack_network_name     = "" # Internal Neutron network name
openstack_floating_ip_pool = "" # External / public network name for floating IPs
openstack_ssh_keypair      = "" # Name of the Nova keypair injected into each VM
openstack_security_groups  = ["default", "k8s"]
openstack_availability_zone = "nova"

# Default Nova flavor – used when a node pool does not specify its own flavor
openstack_flavor_defaults = "m1.large"

# Systems
system_ssh_keys_dir = "~/.ssh/oss" # Directory holding public keys for each system

# Kubernetes - Cluster
cluster_version        = "1.32.7"       # Kubernetes Version
cluster_cni            = "calico"       # Kubernetes Container Network Interface (CNI)
cluster_cni_version    = "3.30.0"       # CNI Version
cluster_cri            = "containerd"   # Kubernetes Container Runtime Interface (CRI)
cluster_cri_version    = "1.7.24"       # CRI Version
cluster_service_subnet = "10.43.0.0/16" # Kubernetes Service Subnet
cluster_pod_subnet     = "10.42.0.0/16" # Kubernetes Pod Subnet
cluster_domain         = ""             # Base DNS domain for this cluster's nodes.
                                            # Nodes will be registered as <hostname>.<cluster_domain>.
                                            # Use the domain that matches your OpenStack tenant's DNS zone.
                                            # HPOS example: tenant_name.hpos4.rnd.sas.com
                                            # Leave empty to default to cluster.local (not recommended for HPOS).

# Kubernetes - Cluster VIP (kube-vip control-plane HA)
cluster_vip_version = "0.7.1"
cluster_vip_ip      = "" # Available IP on the tenant network for the VIP
cluster_vip_fqdn    = "" # FQDN for the VIP – must be resolvable on all nodes

# Kubernetes - Load Balancer
cluster_lb_type = "kube_vip" # Accepted values: kube_vip, metallb

# Load Balancer Addresses
#
#  kube-vip sample:
#    cluster_lb_addresses = [
#      "cidr-default: 192.168.0.200/29",
#      "range-development: 192.168.0.210-192.168.0.219",
#    ]
#
#  MetalLB sample:
#    cluster_lb_addresses = [
#      "192.168.10.0/24",
#    ]
cluster_lb_addresses = []

# Control plane node shared SSH key name (generated by Ansible)
control_plane_ssh_key_name = "cp_ssh"

# =============================================================================
# Cluster Node Pools
#
# - count      : number of instances (used when floating IPs are assigned by OpenStack)
# - flavor     : (optional) override openstack_flavor_defaults for this pool
# - os_disk    : root volume size in GiB for the boot/OS disk.
#                This is a Cinder (block storage) volume — it is NOT limited to
#                the flavor's ephemeral disk size. It is created independently
#                and can be sized based on available Cinder quota.
#                Recommended minimums: control_plane=100, system=100,
#                                      node=350 (for Viya workloads), others=100
# - misc_disks : list of additional Cinder data volume sizes in GiB (e.g. [100, 200])
# =============================================================================
node_pools = {
  # REQUIRED – DO NOT REMOVE or RENAME
  control_plane = {
    count       = 3   # Odd number recommended for HA with kube-vip
    flavor      = "m1.medium"
    os_disk     = 100
    node_taints = []
    node_labels = {}
  },
  # REQUIRED – DO NOT REMOVE or RENAME
  system = {
    count  = 1
    flavor = "m1.xlarge"
    os_disk = 100
    node_taints = []
    node_labels = {
      "kubernetes.azure.com/mode" = "system"
    }
  },
  cas = {
    count  = 3
    flavor = "m1.2xlarge"
    os_disk = 350
    misc_disks = [150, 150]
    node_taints = ["workload.sas.com/class=cas:NoSchedule"]
    node_labels = {
      "workload.sas.com/class" = "cas"
    }
  },
  compute = {
    count  = 1
    flavor = "m1.2xlarge"
    os_disk = 100
    node_taints = ["workload.sas.com/class=compute:NoSchedule"]
    node_labels = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
  },
  stateful = {
    count  = 2
    flavor = "m1.large"
    os_disk = 100
    misc_disks = [150]
    node_taints = ["workload.sas.com/class=stateful:NoSchedule"]
    node_labels = {
      "workload.sas.com/class" = "stateful"
    }
  },
  stateless = {
    count  = 4
    flavor = "m1.large"
    os_disk = 100
    misc_disks = [150]
    node_taints = ["workload.sas.com/class=stateless:NoSchedule"]
    node_labels = {
      "workload.sas.com/class" = "stateless"
    }
  }
}

# Jump server (optional – recommended for air-gapped / NAT environments)
create_jump    = true    # Set false to skip
jump_num_cpu   = 4
jump_memory    = 8092
jump_disk_size = 100
# jump_ip = ""  # Uncomment to pin a specific floating IP; leave commented for auto-assign

# NFS server (optional – used for RWX / shared storage)
create_nfs    = true
nfs_num_cpu   = 4
nfs_memory    = 16384
nfs_disk_size = 400
# nfs_ip = ""  # Uncomment to pin a specific floating IP

# Postgres Servers (optional – remove block if using external Postgres)
postgres_servers = {
  default = {
    server_flavor          = "m1.large"           # Reuses openstack_flavor_defaults if omitted
    server_disk_size       = 128                   # GiB
    server_ip              = ""                    # Leave empty for DHCP / floating IP
    server_version         = 15
    server_ssl             = "off"
    administrator_login    = "postgres"
    administrator_password = "my$up3rS3cretPassw0rd"
  }
}
