---
collections:
  - name: community.general
    version: 8.4.0
  - name: community.postgresql
    version: 3.3.0
  - name: kubernetes.core
    version: 2.4.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.12.0
