# Copyright © 2022-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# TODO: Make "SharedServices" a variable
- name: Create SharedServices database
  ansible.builtin.shell: |
    echo 'CREATE DATABASE "SharedServices";' >> /tmp/postgres_databases.psql
    echo 'GRANT ALL PRIVILEGES ON DATABASE "SharedServices" TO {{ postgres_administrator_login }} ;' >> /tmp/postgres_databases.psql
    psql -f /tmp/postgres_databases.psql
  when: postgres_server_name == "default"
  tags:
    - install
    - update
