# Copyright © 2022-2024, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
- name: Applying taints
  ansible.builtin.shell: |
    kubectl taint nodes -l 'kubernetes.io/hostname in ({{ ansible_hostname }},{{ ansible_fqdn }})' {{ taint }} --overwrite
  with_items: "{{ taints }}"
  loop_control:
    loop_var: taint
  delegate_to: "{{ groups['k8s_control_plane'][0] }}"
  tags:
    - install
    - update
