---
# Handlers for kubeadm role

- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted
    daemon_reload: true

- name: Restart docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    daemon_reload: true

- name: Restart crio
  ansible.builtin.systemd:
    name: crio
    state: restarted
    daemon_reload: true
