# Copyright © 2022-2023, SAS Institute Inc., Cary, NC, USA. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
# Tasks that run on all nodes for initialization and common tasks
- hosts: all
  name: Systems Install - Common
  become: true
  become_user: root
  roles:
    - { role: "systems/{{ deployment_type }}/init" }
    - { role: systems/common }

# NFS Server
- hosts: nfs
  name: System Install - NFS Server
  become: true
  become_user: root
  roles:
    - { role: systems/nfs_server }

# Jump Server
- hosts: jump
  name: System Install - Jump Server
  become: true
  become_user: root
  roles:
    - { role: systems/jump_server }

# Postgres Server
- hosts: postgres
  name: System Install - Postgres Server
  become: true
  become_user: root
  roles:
    - { role: systems/postgres }

# Container Registry Server
- hosts: cr
  name: System Install - CR
  become: true
  become_user: root
  roles:
    - { role: systems/container_registry/harbor }

# Kubernetes - Control Plane
- hosts: k8s_control_plane
  name: System Install - Control Plane
  become: true
  become_user: root
  roles:
    - { role: systems/control_plane }

# Kubernetes - Compute nodes
- hosts: k8s_node
  name: System Install - Compute Nodes
  become: true
  become_user: root
  roles:
    - { role: systems/node }
